#include "mainwindow.h"
#include "ui_mainwindow.h"

MainWindow::MainWindow(ViewModel *_vm, QWidget *parent, std::function<void (QString)> msgLogger)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
    , vm(_vm) {
    ui->setupUi(this);
    Q_UNUSED(msgLogger);
    
    //设置标签页可见性
    auto tabBar = ui->tabWidget->tabBar();
    tabBar->setTabVisible(2,false);
    tabBar->setTabVisible(3,false);
    tabBar->setTabVisible(5,false);
    tabBar->setTabVisible(6,false);
    
    //Observable和信号槽
    // QAction *actionOpen;
    connect(ui->actionOpen,&QAction::triggered,vm,[this]{vm->openFile();});
    // QAction *actionFolder;
    connect(ui->actionFolder,&QAction::triggered,vm,&ViewModel::openFolder);
    // QAction *actionupload_file;
    connect(ui->actionupload_file,&QAction::triggered,vm,[this]{vm->sendFile();});
    // QAction *actionHangup;
    connect(ui->actionHangup,&QAction::triggered,vm,[this]{vm->on_hangup();});
    // QAction *actionDownload;
    connect(ui->actionHangup,&QAction::triggered,vm,&ViewModel::on_download);
    // QAction *actionSync_PAT;
    // connect(ui->actionSync_PAT,&QAction::triggered,vm,&ViewModel::on_download);
    // QAction *actionRefresh;
    connect(ui->actionRefresh,&QAction::triggered,vm,&ViewModel::refresh);
    // QAction *actionShutdown_current;
    connect(ui->actionShutdown_current,&QAction::triggered,vm,&ViewModel::on_shutdown_current);
    // QAction *actionShutdown;
    connect(ui->actionShutdown,&QAction::triggered,vm,&ViewModel::shutdown);
    // QAction *actionTest_RTT;
    connect(ui->actionTest_RTT,&QAction::triggered,vm,&ViewModel::on_test_rtt);
    // QAction *actionRequestFile;
    connect(ui->actionRequestFile,&QAction::triggered,vm,&ViewModel::on_request_file);
    // QAction *actionRemoteCopyFile;
    connect(ui->actionRemoteCopyFile,&QAction::triggered,vm,&ViewModel::startCopyingRemoteFile);
    // QAction *actionSend_message;
    connect(ui->actionSend_message,&QAction::triggered,vm,&ViewModel::sendTestMessage);
    // QAction *actionStart_remote;
    // QAction *actionOpen_DriveCrypto;
    // QAction *actionAdd_file;
    // QAction *actionIncremental_sync_enable;
    // QAction *actionIncremental_sync_disable;
    // QAction *actionExit_Application;
    // QAction *actionHang_up_file_to_dfhn;
    // QAction *actionDownload_file_from_dfhn;
    // QAction *actionRestart_all_applications;
    // QAction *actionrestart;
    // QWidget *centralwidget;
    // QGridLayout *gridLayout;
    // QTabWidget *tabWidget;
    // QWidget *tab_file;
    // QGridLayout *gridLayout_2;
    // QPushButton *pushButton_file_addSchedule;
    // QLabel *label_19;
    // QListWidget *listWidget_schedule;
    // QPushButton *pushButton_file_syncAll;
    // QLabel *label_17;
    // QListWidget *listWidget_file;
    // QPushButton *pushButton_file_deleteCurrentSchedule;
    // QListWidget *listWidget_incremental;
    // QCheckBox *checkBox_file_autoSync;
    // QWidget *tab_deviceList;
    // QGridLayout *gridLayout_7;
    // QTableWidget *tableWidget_deviceList;
    // QGridLayout *gridLayout_12;
    // QFormLayout *formLayout;
    // QLabel *label_24;
    // QLabel *label_sendInfo_currentRate;
    // QLabel *label_25;
    // QLabel *label_sendInfo_rtt;
    // QFormLayout *formLayout_2;
    // QLabel *label_28;
    // QLabel *label_sendInfo_currentPackage;
    // QLabel *label_30;
    // QLabel *label_sendInfo_totalPackege;
    // QLabel *label_29;
    // QLabel *label_sendInfo_progress;
    // QLabel *label_27;
    // QLabel *label_26;
    // QWidget *tab_remoteControl;
    // QGridLayout *gridLayout_9;
    // QPushButton *pushButton_remote_stop;
    // RemoteControlWidget *widget_remoteControl;
    // QWidget *tab_proxy;
    // QGridLayout *gridLayout_6;
    // QTextBrowser *textBrowser_proxy;
    // QPushButton *pushButton_switchProxy;
    // QWidget *tab_settings;
    // QGridLayout *gridLayout_4;
    // QPushButton *pushButton_settings_save;
    // QScrollArea *scrollArea_settings;
    // QWidget *scrollAreaWidgetContents;
    // QGridLayout *gridLayout_8;
    // QSpinBox *spinBox_settings_mqttPort;
    // QLabel *label_15;
    // QLabel *label_11;
    // QLabel *label_2;
    // QLabel *label_21;
    // QFrame *line;
    // QLineEdit *lineEdit_settings_mqttServer;
    // QLabel *label_7;
    // QComboBox *comboBox_settings_uiskin;
    // QHBoxLayout *horizontalLayout_3;
    // QPushButton *pushButton_settings_mode_normal;
    // QPushButton *pushButton_settings_mode_dfhn;
    // QLabel *label_9;
    // QLineEdit *lineEdit_settings_pwd;
    // QHBoxLayout *horizontalLayout;
    // QPushButton *pushButton_settings_recordLog;
    // QPushButton *pushButton_settings_console;
    // QCheckBox *checkBox_settings_ipv6;
    // QLabel *label_5;
    // QLabel *label_8;
    // QLineEdit *lineEdit_settings_username;
    // QLineEdit *lineEdit_settings_description;
    // QLabel *label_16;
    // QLabel *label_6;
    // QLabel *label_18;
    // QLabel *label_4;
    // QPushButton *pushButton_copyId;
    // QComboBox *comboBox_settings_language;
    // QLabel *label_3;
    // QLabel *label_14;
    // QLineEdit *lineEdit_settings_gitubUser;
    // QCheckBox *checkBox_settings_disableNotice;
    // QLabel *label_22;
    // QLabel *label_12;
    // QLabel *label;
    // QLabel *label_10;
    // QPushButton *pushButton_settings_getDefaultPAT;
    // QPushButton *pushButton_settings_requestUI;
    // QCheckBox *checkBox_settings_recordLog;
    // QLabel *label_13;
    // QLineEdit *lineEdit_settings_githubPAT;
    // QLabel *label_23;
    // QWidget *tab_userRules;
    // QGridLayout *gridLayout_5;
    // QTextBrowser *textBrowser_userRule_2;
    // QTextBrowser *textBrowser_userRule_1;
    // QWidget *tab_debug;
    // QGridLayout *gridLayout_3;
    // QPushButton *pushButton_debug1;
    // QTextBrowser *textBrowser_debug1;
    // QTextEdit *textEdit_debug1;
    // QWidget *tab_route;
    // QGridLayout *gridLayout_10;
    // QCommandLinkButton *commandLinkButton_route_page6;
    // QLabel *label_20;
    // QCommandLinkButton *commandLinkButton_route_page5;
    // QCommandLinkButton *commandLinkButton_route_page3;
    // QSpacerItem *verticalSpacer;
    // QCommandLinkButton *commandLinkButton_route_page2;
    // QCommandLinkButton *commandLinkButton_route_help;
    // QMenuBar *menubar;
    // QMenu *menuFile;
    // QMenu *menuApplication_A;
    // QMenu *menu;
    // QStatusBar *statusBar;
}

MainWindow::~MainWindow() {
    delete ui;
}
